// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2_Luis_Miguel_Jerez_Caceres.Server.DAL;

#nullable disable

namespace Parcial2_Luis_Miguel_Jerez_Caceres.Server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230925225700_Entrada")]
    partial class Entrada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Parcial2_Luis_Miguel_Jerez_Caceres.Shared.Models.Entradas", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CantidadProducida")
                        .HasColumnType("REAL");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<float>("PesoTotal")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntradaId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Parcial2_Luis_Miguel_Jerez_Caceres.Shared.Models.EntradasDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CantidadUtilizada")
                        .HasColumnType("REAL");

                    b.Property<int>("EntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("EntradaId");

                    b.ToTable("EntradasDetalle");
                });

            modelBuilder.Entity("Parcial2_Luis_Miguel_Jerez_Caceres.Shared.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Existencia")
                        .HasColumnType("REAL");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Descripcion = "Maní",
                            Existencia = 40f,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 2,
                            Descripcion = "Pistachos",
                            Existencia = 600f,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 3,
                            Descripcion = "Pasas",
                            Existencia = 500f,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 4,
                            Descripcion = "Ciruelas",
                            Existencia = 700f,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 5,
                            Descripcion = "Mixto MPP 0.5lb",
                            Existencia = 0f,
                            Tipo = 1
                        },
                        new
                        {
                            ProductoId = 6,
                            Descripcion = "Mixto MPC 0.5lb",
                            Existencia = 0f,
                            Tipo = 1
                        },
                        new
                        {
                            ProductoId = 7,
                            Descripcion = "Mixto MPP 0.2lb",
                            Existencia = 0f,
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("Parcial2_Luis_Miguel_Jerez_Caceres.Shared.Models.EntradasDetalle", b =>
                {
                    b.HasOne("Parcial2_Luis_Miguel_Jerez_Caceres.Shared.Models.Entradas", null)
                        .WithMany("EntradasDetalles")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parcial2_Luis_Miguel_Jerez_Caceres.Shared.Models.Entradas", b =>
                {
                    b.Navigation("EntradasDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
